# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NilsWaldowski.de
email: me@nilswaldowski.de
description: > # this means to ignore newlines until "baseurl:"
  Artikel über moderne Webentwicklung, Performance, Progressive Enhancement, Frontend- und Design-Workflows.
keywords: SCSS, JS, Javascript, jQuery, Progressive Enhancement, Frontend, RWD, Performance, Web, Workflows
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nilswaldowski.de" # the base hostname & protocol for your site
twitter_username: NilsWaldowski
github_username:  NilsWaldowski

# DEVELOPMENT
css: /Dist/Css/screen.css
js-require: /Dist/Vendor/requirejs/require.js
js-require_config: /Dist/Javascript/config
js-enhancement: /Dist/JavascriptEnhancement/progressive.enhancement.js
js-html5shiv: /Dist/JavascriptEnhancement/html5shiv.js
fonts-src: https://fonts.googleapis.com/css?family=Open+Sans|Merriweather:300

# PRODUCTION
css_production: /Dist_prod/Css/screen.min.css
js-compiled_production: /Dist_prod/Javascript/Build/javascript.min.js
js-enhancement_production: /Dist_prod/JavascriptEnhancement/progressive.enhancement.min.js
js-html5shiv_production: /Dist_prod/JavascriptEnhancement/html5shiv.min.js

# Build settings
markdown: kramdown
