# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NilsWaldowski.de
email: me@nilswaldowski.de
description: > # this means to ignore newlines until "baseurl:"
  Artikel über moderne Webentwicklung, Performance, Progressive Enhancement, Frontend- und Design-Workflows.
keywords: SCSS, JS, Javascript, jQuery, Progressive Enhancement, Frontend, RWD, Performance, Web, Workflows
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nilswaldowski.de" # the base hostname & protocol for your site
twitter_username: NilsWaldowski
github_username:  NilsWaldowski
exclude: [node_modules, 01-src, 03-internals]

# DEVELOPMENT
css: /dist/stylesheets/screen.css
css-framework: /dist/stylesheets/framework.css
js-core: /dist/javascript-core/core.js
js-config: /dist/javascript/config.js
js-cookie: /dist/javascript-inline/cookie.js
js-fontobserver: /dist/javascript-inline/fontfaceobserver.js
js-fontobserver-config: /dist/fontfaceobserver-config.js

# PRODUCTION
css--prod: /dist_prod/stylesheets/screen.min.css
css-framework--prod: /dist_prod/stylesheets/framework.min.css
js-build: /dist_prod/javascript/build/main.js
js-cookie--prod: /dist_prod/javascript-inline/cookie.min.js
js-fontobserver--prod: /dist_prod/javascript-inline/fontfaceobserver.min.js
js-fontobserver-config--prod: /dist_prod/javascript-inline/fontfaceobserver-config.min.js

# Build settings
markdown: kramdown

# build: $ JEKYLL_ENV=production jekyll build

